/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package restaurante;

import entorno.Conectar;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import jugo.Jugo;

/**
 *
 * @author CAMILO
 */
public class FrmJugo extends javax.swing.JFrame {

    static List<Jugo> jugo = new ArrayList<>();
    private int registroModificar;
    Conectar con = new Conectar();
    Connection cn = con.conexion();

    public void setRegistroModificar(int registroModificar) {
        this.registroModificar = registroModificar;
    }

    public static List<Jugo> getJugo() {
        return jugo;
    }

    /**
     * Creates new form Jugo
     */
    public FrmJugo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        nombreJugo = new javax.swing.JLabel();
        txtNombreJugo = new javax.swing.JTextField();
        cantidadJugo = new javax.swing.JLabel();
        txtCantidadJugo = new javax.swing.JTextField();
        precioJugo = new javax.swing.JLabel();
        txtPrecioJugo = new javax.swing.JTextField();
        btnVolver = new javax.swing.JButton();
        btnregistrar = new javax.swing.JButton();
        jComboBoxIdiomaJugo = new javax.swing.JComboBox<>();
        fondoJugo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nombreJugo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        nombreJugo.setForeground(new java.awt.Color(0, 51, 51));
        nombreJugo.setText("Nombre del Jugo");
        jPanel1.add(nombreJugo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 170, -1));
        jPanel1.add(txtNombreJugo, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, 210, 50));

        cantidadJugo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cantidadJugo.setForeground(new java.awt.Color(0, 51, 51));
        cantidadJugo.setText("Cantidad de Jugo");
        jPanel1.add(cantidadJugo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, -1, -1));
        jPanel1.add(txtCantidadJugo, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 270, 210, 50));

        precioJugo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        precioJugo.setForeground(new java.awt.Color(0, 51, 51));
        precioJugo.setText("Precio del Jugo");
        jPanel1.add(precioJugo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, 140, -1));

        txtPrecioJugo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrecioJugoActionPerformed(evt);
            }
        });
        jPanel1.add(txtPrecioJugo, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 370, 210, 50));

        btnVolver.setBackground(new java.awt.Color(255, 255, 102));
        btnVolver.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnVolver.setForeground(new java.awt.Color(0, 51, 51));
        btnVolver.setIcon(new javax.swing.ImageIcon("C:\\Users\\CAMILO\\Downloads\\exit.png")); // NOI18N
        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        jPanel1.add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 520, 190, -1));

        btnregistrar.setBackground(new java.awt.Color(255, 255, 102));
        btnregistrar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnregistrar.setForeground(new java.awt.Color(0, 51, 51));
        btnregistrar.setIcon(new javax.swing.ImageIcon("C:\\Users\\CAMILO\\Downloads\\registraricon.png")); // NOI18N
        btnregistrar.setText("Registrar");
        btnregistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnregistrarActionPerformed(evt);
            }
        });
        jPanel1.add(btnregistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 520, 190, 70));

        jComboBoxIdiomaJugo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Español", "Ingles" }));
        jComboBoxIdiomaJugo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxIdiomaJugoActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBoxIdiomaJugo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        fondoJugo.setIcon(new javax.swing.ImageIcon("C:\\Users\\CAMILO\\Downloads\\jugos (2) (1).jpg")); // NOI18N
        jPanel1.add(fondoJugo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 640));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPrecioJugoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecioJugoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecioJugoActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        // TODO add your handling code here:
        menu menus = new menu();
        menus.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnregistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnregistrarActionPerformed
        // TODO add your handling code here:
        String nombreJugo = this.txtNombreJugo.getText();
        int precioJugo = Integer.parseInt(this.txtPrecioJugo.getText());
        int cantidadJugo = Integer.parseInt(this.txtCantidadJugo.getText());
        Jugo Jugos = new Jugo(nombreJugo, precioJugo, cantidadJugo);

        if (btnregistrar.getText() == "Registrar") {
            jugo.add(Jugos);
              try {
                PreparedStatement ps = cn.prepareStatement("INSERT INTO jugo(nombre,precio,cantidad,estado)VALUES(?,?,?,?)");
                ps.setString(1, nombreJugo);
                ps.setInt(2, precioJugo);
                ps.setInt(3, cantidadJugo);
                ps.setString(4, "A");
                ps.executeUpdate();
                JOptionPane.showMessageDialog(null, "Jugo Registrado ");

            } catch (SQLException e) {
                System.err.println(e);
                JOptionPane.showMessageDialog(null, "Error al registrar el Jugo ");

            }

        } else if (btnregistrar.getText() == "modificar") {
              try {
                
                PreparedStatement ps = cn.prepareStatement("UPDATE jugo SET nombre='" + nombreJugo + "', precio=" + precioJugo + ", cantidad=" + cantidadJugo + " WHERE id=" + jugo.get(registroModificar).id);
                int respuesta=ps.executeUpdate();
                if (respuesta>0) {
                    JOptionPane.showMessageDialog(null, "Actualizacion exitosa");
                    
                }
            } catch (SQLException e) {
                System.err.println("Error al actualizar"+e);
            }
        }

        limpiarCampos();

    }//GEN-LAST:event_btnregistrarActionPerformed

    private void jComboBoxIdiomaJugoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxIdiomaJugoActionPerformed
        // TODO add your handling code here:
        String seleccion = (String) jComboBoxIdiomaJugo.getSelectedItem();

        if (seleccion == "Ingles") {
            this.nombreJugo.setText("Name of Juice");
            this.cantidadJugo.setText("Quantity of Juice");
            this.precioJugo.setText("Price of Juice");
            this.btnVolver.setText("Return");
            this.btnregistrar.setText("Add");

        } else if (seleccion == "Español") {
            this.nombreJugo.setText("Nombre del Jugo");
            this.cantidadJugo.setText("Cantidad de Jugo");
            this.precioJugo.setText("Preio del Jugo");
            this.btnVolver.setText("Volver");
            this.btnregistrar.setText("Registrar");

        }
    }//GEN-LAST:event_jComboBoxIdiomaJugoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmJugo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmJugo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmJugo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmJugo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmJugo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVolver;
    private javax.swing.JButton btnregistrar;
    private javax.swing.JLabel cantidadJugo;
    private javax.swing.JLabel fondoJugo;
    private javax.swing.JComboBox<String> jComboBoxIdiomaJugo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel nombreJugo;
    private javax.swing.JLabel precioJugo;
    private javax.swing.JTextField txtCantidadJugo;
    private javax.swing.JTextField txtNombreJugo;
    private javax.swing.JTextField txtPrecioJugo;
    // End of variables declaration//GEN-END:variables

    private void limpiarCampos() {
        this.txtNombreJugo.setText("");
        this.txtCantidadJugo.setText("");
        this.txtPrecioJugo.setText("");
        //this.txtLitrosJugo.setText("");
    }

    void modificarJugo() {
        btnregistrar.setText("modificar");
        System.out.println("registro Jugo" + this.registroModificar);
        this.txtNombreJugo.setText(jugo.get(this.registroModificar).nombreJugo);
        this.txtPrecioJugo.setText(Integer.toString(jugo.get(this.registroModificar).precioJugo));
        this.txtCantidadJugo.setText(Integer.toString(jugo.get(this.registroModificar).cantidadJugo));
          jugo.forEach(Jugo -> {
            System.out.println(Jugo.id + "\t" + Jugo.nombreJugo + "\t" + Jugo.precioJugo + "\t" + Jugo.cantidadJugo);
        });

    }
}
