/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package restaurante;

import entorno.Conectar;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import platoPrincipal.PlatoPrincipal;

/**
 *
 * @author CAMILO
 */
public class FrmPlatosPrincipales extends javax.swing.JFrame {

    static List<PlatoPrincipal> platosPrincipales = new ArrayList<>();

    public void setPlatosPrincipales(List<PlatoPrincipal> platosPrincipales) {
        FrmPlatosPrincipales.platosPrincipales = platosPrincipales;
    }
    private int registroModificar;
    //atributos conexion
    Conectar con = new Conectar();
    Connection cn = con.conexion();

    public void setRegistroModificar(int registroModificar) {
        this.registroModificar = registroModificar;
    }

    public static List<PlatoPrincipal> getPlatosPrincipales() {
        return platosPrincipales;
    }

    /**
     * Creates new form PlatosPrincipales
     */
    public FrmPlatosPrincipales() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        platosp = new javax.swing.JLabel();
        txtNombrePlato = new javax.swing.JTextField();
        cantidadplatos = new javax.swing.JLabel();
        txtCantidadPlatos = new javax.swing.JTextField();
        PrecioPlatos = new javax.swing.JLabel();
        txtPrecioPlatos = new javax.swing.JTextField();
        btnVolver = new javax.swing.JButton();
        btnregistrar = new javax.swing.JButton();
        btnConsola = new javax.swing.JButton();
        jComboBoxIdiomaPlato = new javax.swing.JComboBox<>();
        fondoplato = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(480, 480));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        platosp.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        platosp.setForeground(new java.awt.Color(51, 0, 0));
        platosp.setText("Platos Principales");
        jPanel1.add(platosp, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 160, 20));

        txtNombrePlato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombrePlatoActionPerformed(evt);
            }
        });
        jPanel1.add(txtNombrePlato, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, 220, 40));

        cantidadplatos.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cantidadplatos.setForeground(new java.awt.Color(51, 0, 0));
        cantidadplatos.setText("Cantidad de Platos");
        jPanel1.add(cantidadplatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 190, -1));
        jPanel1.add(txtCantidadPlatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 180, 220, 40));

        PrecioPlatos.setBackground(new java.awt.Color(255, 51, 0));
        PrecioPlatos.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        PrecioPlatos.setForeground(new java.awt.Color(51, 0, 0));
        PrecioPlatos.setText("Precios de los Platos");
        jPanel1.add(PrecioPlatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 180, -1));
        jPanel1.add(txtPrecioPlatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 280, 220, 40));

        btnVolver.setBackground(new java.awt.Color(255, 204, 153));
        btnVolver.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnVolver.setForeground(new java.awt.Color(51, 0, 0));
        btnVolver.setIcon(new javax.swing.ImageIcon("C:\\Users\\CAMILO\\Downloads\\exit.png")); // NOI18N
        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        jPanel1.add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, 200, -1));

        btnregistrar.setBackground(new java.awt.Color(255, 204, 153));
        btnregistrar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnregistrar.setForeground(new java.awt.Color(51, 0, 0));
        btnregistrar.setIcon(new javax.swing.ImageIcon("C:\\Users\\CAMILO\\Downloads\\registraricon.png")); // NOI18N
        btnregistrar.setText("Registrar");
        btnregistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnregistrarActionPerformed(evt);
            }
        });
        jPanel1.add(btnregistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 430, 180, 70));

        btnConsola.setBackground(new java.awt.Color(255, 204, 153));
        btnConsola.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnConsola.setForeground(new java.awt.Color(51, 0, 0));
        btnConsola.setText("Consola");
        btnConsola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsolaActionPerformed(evt);
            }
        });
        jPanel1.add(btnConsola, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 530, 160, 40));

        jComboBoxIdiomaPlato.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Español", "Ingles" }));
        jComboBoxIdiomaPlato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxIdiomaPlatoActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBoxIdiomaPlato, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        fondoplato.setIcon(new javax.swing.ImageIcon("C:\\Users\\CAMILO\\Downloads\\sushi (1) (1).jpg")); // NOI18N
        fondoplato.setPreferredSize(new java.awt.Dimension(600, 600));
        jPanel1.add(fondoplato, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 630));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 630, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 630, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombrePlatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombrePlatoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombrePlatoActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        // TODO add your handling code here:
        menu menus = new menu();
        menus.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnregistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnregistrarActionPerformed
        // TODO add your handling code here:
        String nombre = this.txtNombrePlato.getText();
        int Precio = Integer.parseInt(this.txtPrecioPlatos.getText());
        int Cantidad = Integer.parseInt(this.txtCantidadPlatos.getText());
        PlatoPrincipal plato = new PlatoPrincipal(nombre, Precio, Cantidad);
        platosPrincipales.add(plato);
        if (btnregistrar.getText() == "Registrar") {
            try {
                PreparedStatement ps = cn.prepareStatement("INSERT INTO platoprincipal(nombre,precio,cantidad,estado)VALUES(?,?,?,?)");
                ps.setString(1, nombre);
                ps.setInt(2, Precio);
                ps.setInt(3, Cantidad);
                ps.setString(4, "A");
                ps.executeUpdate();
                JOptionPane.showMessageDialog(null, "Plato Registrado ");

            } catch (SQLException e) {
                System.err.println(e);
                JOptionPane.showMessageDialog(null, "Error al registrar Plato ");

            }

        } else if (btnregistrar.getText() == "modificar") {
            //System.out.println(this.registroModificar);
            //platosPrincipales.set(this.registroModificar, plato);
            try {
                
                PreparedStatement ps = cn.prepareStatement("UPDATE platoprincipal SET nombre='" + nombre + "', precio=" + Precio + ", cantidad=" + Cantidad + " WHERE id=" + platosPrincipales.get(registroModificar).id);
                int respuesta=ps.executeUpdate();
                if (respuesta>0) {
                    JOptionPane.showMessageDialog(null, "Actualizacion exitosa");
                    
                }
            } catch (SQLException e) {
                System.err.println("Error al actualizar"+e);
            }
        }
        limpiarCampos();


    }//GEN-LAST:event_btnregistrarActionPerformed

    private void btnConsolaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsolaActionPerformed
        // TODO add your handling code here:
        platosPrincipales.forEach(platosPrincipales -> {
            System.out.println("Nombre \tCantidad\t Precio");
            System.out.println(platosPrincipales.nombrePlato + "\t" + platosPrincipales.cantidad + "\t" + platosPrincipales.precio);

        });

    }//GEN-LAST:event_btnConsolaActionPerformed

    private void jComboBoxIdiomaPlatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxIdiomaPlatoActionPerformed
        // TODO add your handling code here:
        String seleccion = (String) jComboBoxIdiomaPlato.getSelectedItem();
        if (seleccion == "Ingles") {
            this.platosp.setText("Main Courses");
            this.cantidadplatos.setText("Quantity of Dishes");
            this.PrecioPlatos.setText("Price of Dishes");
            this.btnregistrar.setText("Add");
            this.btnVolver.setText("Return");
            this.btnConsola.setText("Console");

        } else if (seleccion == "Español") {
            this.platosp.setText("Platos Principales");
            this.cantidadplatos.setText("Cantidad Platos");
            this.PrecioPlatos.setText("Precio de los Platos");
            this.btnregistrar.setText("Registrar");
            this.btnVolver.setText("Volver");
            this.btnConsola.setText("Consola");
        }
    }//GEN-LAST:event_jComboBoxIdiomaPlatoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPlatosPrincipales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPlatosPrincipales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPlatosPrincipales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPlatosPrincipales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPlatosPrincipales().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel PrecioPlatos;
    private javax.swing.JButton btnConsola;
    private javax.swing.JButton btnVolver;
    private javax.swing.JButton btnregistrar;
    private javax.swing.JLabel cantidadplatos;
    private javax.swing.JLabel fondoplato;
    private javax.swing.JComboBox<String> jComboBoxIdiomaPlato;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel platosp;
    private javax.swing.JTextField txtCantidadPlatos;
    private javax.swing.JTextField txtNombrePlato;
    private javax.swing.JTextField txtPrecioPlatos;
    // End of variables declaration//GEN-END:variables

    private void limpiarCampos() {
        this.txtNombrePlato.setText("");
        this.txtPrecioPlatos.setText("");
        this.txtCantidadPlatos.setText("");
    }

    void modificarPlato() {
        btnregistrar.setText("modificar");
        System.out.println("registro plato" + this.registroModificar);
       this.txtNombrePlato.setText(platosPrincipales.get(this.registroModificar).nombrePlato);
       this.txtPrecioPlatos.setText(Integer.toString(platosPrincipales.get(this.registroModificar).precio));
       this.txtCantidadPlatos.setText(Integer.toString(platosPrincipales.get(this.registroModificar).cantidad));
        platosPrincipales.forEach(platosPrincipales -> {
            System.out.println(platosPrincipales.id + "\t" + platosPrincipales.nombrePlato + "\t" + platosPrincipales.precio + "\t" + platosPrincipales.cantidad);
        });
    }
}
