/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package restaurante;

import entorno.Conectar;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import postre.Postre;

/**
 *
 * @author CAMILO
 */
public class FrmPostre extends javax.swing.JFrame {

    static List<Postre> Postres = new ArrayList<>();
    private int registroModificar;
    Conectar con = new Conectar();
    Connection cn = con.conexion();

    public void setRegistroModificar(int registroModificar) {
        this.registroModificar = registroModificar;
    }

    public static List<Postre> getPostres() {
        return Postres;
    }

    /**
     * Creates new form Postre
     */
    public FrmPostre() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        postre = new javax.swing.JLabel();
        txtNombrePostre = new javax.swing.JTextField();
        cantidad = new javax.swing.JLabel();
        txtCantidadPostre = new javax.swing.JTextField();
        preciopostre = new javax.swing.JLabel();
        txtPrecioPostre = new javax.swing.JTextField();
        btnVolver = new javax.swing.JButton();
        btnRegistrar = new javax.swing.JButton();
        jComboBoxIdiomaPostre = new javax.swing.JComboBox<>();
        fonPostre = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        postre.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        postre.setForeground(new java.awt.Color(0, 0, 0));
        postre.setText("Nombre del Postre");
        jPanel1.add(postre, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 180, -1));
        jPanel1.add(txtNombrePostre, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 150, 240, 40));

        cantidad.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cantidad.setForeground(new java.awt.Color(0, 0, 0));
        cantidad.setText("Cantidad de Postres");
        jPanel1.add(cantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, -1, -1));

        txtCantidadPostre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCantidadPostreActionPerformed(evt);
            }
        });
        jPanel1.add(txtCantidadPostre, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 220, 240, 40));

        preciopostre.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        preciopostre.setForeground(new java.awt.Color(0, 0, 0));
        preciopostre.setText("Precio de los Postres");
        jPanel1.add(preciopostre, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 180, -1));
        jPanel1.add(txtPrecioPostre, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 290, 240, 40));

        btnVolver.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnVolver.setForeground(new java.awt.Color(0, 0, 0));
        btnVolver.setIcon(new javax.swing.ImageIcon("C:\\Users\\CAMILO\\Downloads\\exit.png")); // NOI18N
        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        jPanel1.add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 460, -1, -1));

        btnRegistrar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnRegistrar.setForeground(new java.awt.Color(0, 0, 0));
        btnRegistrar.setIcon(new javax.swing.ImageIcon("C:\\Users\\CAMILO\\Downloads\\registraricon.png")); // NOI18N
        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 470, 180, 60));

        jComboBoxIdiomaPostre.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Español", "Ingles" }));
        jComboBoxIdiomaPostre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxIdiomaPostreActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBoxIdiomaPostre, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        fonPostre.setIcon(new javax.swing.ImageIcon("C:\\Users\\CAMILO\\Downloads\\postre (1).jpg")); // NOI18N
        jPanel1.add(fonPostre, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -50, 630, 740));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCantidadPostreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCantidadPostreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantidadPostreActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        // TODO add your handling code here:
        menu menus = new menu();
        menus.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        // TODO add your handling code here:
        String nombrePostre = this.txtNombrePostre.getText();
        int precioPostre = Integer.parseInt(this.txtPrecioPostre.getText());
        int cantidadPostre = Integer.parseInt(this.txtCantidadPostre.getText());
        Postre postres = new Postre(nombrePostre, precioPostre, cantidadPostre);
          Postres.add(postres);

        if (btnRegistrar.getText() == "Registrar") {
             try {
                PreparedStatement ps = cn.prepareStatement("INSERT INTO postre(nombre,precio,cantidad,estado)VALUES(?,?,?,?)");
                ps.setString(1, nombrePostre);
                ps.setInt(2, precioPostre);
                ps.setInt(3, cantidadPostre);
                ps.setString(4, "A");
                ps.executeUpdate();
                JOptionPane.showMessageDialog(null, "Postre Registrado ");

            } catch (SQLException e) {
                System.err.println(e);
                JOptionPane.showMessageDialog(null, "Error al registrar Postre ");

            }
          

        } else if (btnRegistrar.getText() == "modificar") {
            System.out.println(this.registroModificar);
            Postres.set(this.registroModificar, postres);
        }

        limpiarCampos();
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void jComboBoxIdiomaPostreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxIdiomaPostreActionPerformed
        // TODO add your handling code here:
        String seleccion = (String) jComboBoxIdiomaPostre.getSelectedItem();
        if (seleccion == "Ingles") {
            this.postre.setText("Name of Desserts");
            this.preciopostre.setText("Price of Desserts");
            this.cantidad.setText("Quantity of Desserts");
            this.btnRegistrar.setText("Add");
            this.btnVolver.setText("Return");

        } else if (seleccion == "Español") {
            this.postre.setText("Nombre del Postre");
            this.preciopostre.setText("Precio de los Postres");
            this.cantidad.setText("Cantidad de Postres");
            this.btnRegistrar.setText("Registrar");
            this.btnVolver.setText("Volver");
        }
    }//GEN-LAST:event_jComboBoxIdiomaPostreActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPostre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPostre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPostre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPostre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPostre().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel cantidad;
    private javax.swing.JLabel fonPostre;
    private javax.swing.JComboBox<String> jComboBoxIdiomaPostre;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel postre;
    private javax.swing.JLabel preciopostre;
    private javax.swing.JTextField txtCantidadPostre;
    private javax.swing.JTextField txtNombrePostre;
    private javax.swing.JTextField txtPrecioPostre;
    // End of variables declaration//GEN-END:variables

    private void limpiarCampos() {
        this.txtNombrePostre.setText("");
        this.txtPrecioPostre.setText("");
        this.txtCantidadPostre.setText("");
    }

    void modificarPostre() {
        btnRegistrar.setText("modificar");
        System.out.println("registro Postre" + this.registroModificar);
        this.txtNombrePostre.setText(Postres.get(this.registroModificar).nombrePostre);
        this.txtPrecioPostre.setText(Integer.toString(Postres.get(this.registroModificar).precioPostre));
        this.txtCantidadPostre.setText(Integer.toString(Postres.get(this.registroModificar).cantidadPostre));

    }
}
