/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package restaurante;

import entorno.Conectar;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import sopa.Sopa;

/**
 *
 * @author CAMILO
 */
public class FrmSopa extends javax.swing.JFrame {

    static List<Sopa> sopa = new ArrayList<>();
    private int registroModificar;
    Conectar con = new Conectar();
    Connection cn = con.conexion();

    public void setRegistroModificar(int registroModificar) {
        this.registroModificar = registroModificar;
    }

    public static List<Sopa> getSopa() {
        return sopa;
    }

    public static void setSopa(List<Sopa> sopa) {
        FrmSopa.sopa = sopa;
    }

    /**
     * Creates new form Sopa
     */
    public FrmSopa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        nombreSopa = new javax.swing.JLabel();
        txtNombreSopa = new javax.swing.JTextField();
        cantidadsopa = new javax.swing.JLabel();
        txtCantidadSopa = new javax.swing.JTextField();
        precioSopa = new javax.swing.JLabel();
        txtPrecioSopa = new javax.swing.JTextField();
        btnVolver = new javax.swing.JButton();
        btnRegistrar = new javax.swing.JButton();
        jComboBoxIdiomaSopa = new javax.swing.JComboBox<>();
        fondoSopa = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nombreSopa.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        nombreSopa.setForeground(new java.awt.Color(0, 0, 0));
        nombreSopa.setText("Nombre de la Sopa");
        jPanel1.add(nombreSopa, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, -1, -1));

        txtNombreSopa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreSopaActionPerformed(evt);
            }
        });
        jPanel1.add(txtNombreSopa, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 60, 200, 50));

        cantidadsopa.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cantidadsopa.setForeground(new java.awt.Color(0, 0, 0));
        cantidadsopa.setText("Cantidad de Sopas");
        jPanel1.add(cantidadsopa, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        txtCantidadSopa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCantidadSopaActionPerformed(evt);
            }
        });
        jPanel1.add(txtCantidadSopa, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 170, 200, 50));

        precioSopa.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        precioSopa.setForeground(new java.awt.Color(0, 0, 0));
        precioSopa.setText("Precio de las Sopas");
        jPanel1.add(precioSopa, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, -1, -1));

        txtPrecioSopa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrecioSopaActionPerformed(evt);
            }
        });
        jPanel1.add(txtPrecioSopa, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 260, 200, 50));

        btnVolver.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnVolver.setForeground(new java.awt.Color(0, 0, 0));
        btnVolver.setIcon(new javax.swing.ImageIcon("C:\\Users\\CAMILO\\Downloads\\exit.png")); // NOI18N
        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        jPanel1.add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 470, -1, -1));

        btnRegistrar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnRegistrar.setForeground(new java.awt.Color(0, 0, 0));
        btnRegistrar.setIcon(new javax.swing.ImageIcon("C:\\Users\\CAMILO\\Downloads\\registraricon.png")); // NOI18N
        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 470, 170, 70));

        jComboBoxIdiomaSopa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Español", "Ingles" }));
        jComboBoxIdiomaSopa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxIdiomaSopaActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBoxIdiomaSopa, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        fondoSopa.setIcon(new javax.swing.ImageIcon("C:\\Users\\CAMILO\\Downloads\\sopa (1) (1).jpg")); // NOI18N
        jPanel1.add(fondoSopa, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 630));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreSopaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreSopaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreSopaActionPerformed

    private void txtCantidadSopaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCantidadSopaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantidadSopaActionPerformed

    private void txtPrecioSopaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecioSopaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecioSopaActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        // TODO add your handling code here:
        menu menus = new menu();
        menus.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        // TODO add your handling code here:
        String nombreSopa = this.txtNombreSopa.getText();
        int precioSopa = Integer.parseInt(this.txtPrecioSopa.getText());
        int cantidadSopa = Integer.parseInt(this.txtCantidadSopa.getText());
        Sopa sopas = new Sopa(nombreSopa, precioSopa, cantidadSopa);
        sopa.add(sopas);
        if (btnRegistrar.getText() == "Registrar") {
            
             try {
                PreparedStatement ps = cn.prepareStatement("INSERT INTO sopa(nombre,precio,cantidad,estado)VALUES(?,?,?,?)");
                ps.setString(1, nombreSopa);
                ps.setInt(2, precioSopa);
                ps.setInt(3, cantidadSopa);
                ps.setString(4, "A");
                ps.executeUpdate();
                JOptionPane.showMessageDialog(null, "Sopa Registrada ");

            } catch (SQLException e) {
                System.err.println(e);
                JOptionPane.showMessageDialog(null, "Error al registrar Sopa ");

            }

        } else if (btnRegistrar.getText() == "modificar") {
           try {
                
                PreparedStatement ps = cn.prepareStatement("UPDATE sopa SET nombre='" + nombreSopa + "', precio=" + precioSopa + ", cantidad=" + cantidadSopa + " WHERE id=" + sopa.get(registroModificar).id);
                int respuesta=ps.executeUpdate();
                if (respuesta>0) {
                    JOptionPane.showMessageDialog(null, "Actualizacion exitosa");
                    
                }
            } catch (SQLException e) {
                System.err.println("Error al actualizar"+e);
            }
        }

        limpiarCampos();
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void jComboBoxIdiomaSopaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxIdiomaSopaActionPerformed
        // TODO add your handling code here:
        String seleccion = (String) jComboBoxIdiomaSopa.getSelectedItem();
        if (seleccion == "Ingles") {
            this.nombreSopa.setText("Name Soups");
            this.cantidadsopa.setText("Quantity of Soups");
            this.precioSopa.setText("Price of Soups");
            this.btnRegistrar.setText("Add");
            this.btnVolver.setText("Return");

        } else if (seleccion == "Español") {
            this.nombreSopa.setText("Nombre de las Sopas");
            this.cantidadsopa.setText("Cantidad de Sopas");
            this.precioSopa.setText("Precio de la Sopas");
            this.btnRegistrar.setText("Registrar");
            this.btnVolver.setText("Volver");
        }
    }//GEN-LAST:event_jComboBoxIdiomaSopaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmSopa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmSopa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmSopa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmSopa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmSopa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel cantidadsopa;
    private javax.swing.JLabel fondoSopa;
    private javax.swing.JComboBox<String> jComboBoxIdiomaSopa;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel nombreSopa;
    private javax.swing.JLabel precioSopa;
    private javax.swing.JTextField txtCantidadSopa;
    private javax.swing.JTextField txtNombreSopa;
    private javax.swing.JTextField txtPrecioSopa;
    // End of variables declaration//GEN-END:variables

    private void limpiarCampos() {
        this.txtNombreSopa.setText("");
        this.txtPrecioSopa.setText("");
        this.txtCantidadSopa.setText("");
    }

    void modificarSopa() {
        btnRegistrar.setText("modificar");
        System.out.println("registro Sopa" + this.registroModificar);
        this.txtNombreSopa.setText(sopa.get(this.registroModificar).nombreSopa);
        this.txtPrecioSopa.setText(Integer.toString(sopa.get(this.registroModificar).precioSopa));
        this.txtCantidadSopa.setText(Integer.toString(sopa.get(this.registroModificar).cantidadSopa));
         sopa.forEach(sopa -> {
            System.out.println(sopa.id + "\t" + sopa.nombreSopa + "\t" + sopa.precioSopa + "\t" + sopa.cantidadSopa);
        });

    }
}
